### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ChickenNuggers** [ChickenNuggers/luacrypto#1]
Feel free to comment suggesting more algorithms. Please don't spam with pseudocode; instead, use a paste service.

## Base Conversion

 * [ ] int -> base table
 * [ ] string -> base table
 * [ ] base table -> base string (`table.concat`)
